#!/bin/bash
# =============================================================================
# OCP Lab Portal — DNS (BIND) + HAProxy infrastructure setup
#
# One-time setup for predefined cluster slots (upi1, upi2, upi3).
# After this runs once, no service restarts are needed when deploying
# or deleting clusters — HAProxy health checks handle backend availability.
#
# Usage: ./cluster-infra-setup.sh
#
# Prerequisites: bind (named), haproxy, libvirt must be installed.
# This script will NOT install packages — it only configures them.
# =============================================================================
set -euo pipefail

# Signature used to identify configs managed by this script
MANAGED_BY="# Managed by: OCP Lab Portal (cluster-infra-setup.sh)"

OCP_LAB_CONF="/etc/ocp-lab.conf"
SUBNET="192.168.122"
BRIDGE_IP="${SUBNET}.1"
HAPROXY_CFG="/etc/haproxy/haproxy.cfg"

# --- Load config from /etc/ocp-lab.conf (generated by portal setup wizard) ---
if [ -f "$OCP_LAB_CONF" ]; then
    echo "Reading config from $OCP_LAB_CONF"
    # shellcheck source=/dev/null
    source "$OCP_LAB_CONF"
fi

# Allow env/arg overrides
DOMAIN="${BASE_DOMAIN:-example.com}"

# Parse CLUSTER_SLOTS (format: "name1:offset1 name2:offset2 ...")
# Fall back to defaults if not set
CLUSTER_SLOTS="${CLUSTER_SLOTS:-cluster1:110 cluster2:120 cluster3:130}"

declare -A CLUSTERS=()
CLUSTER_ORDER=()
for entry in $CLUSTER_SLOTS; do
    cname="${entry%%:*}"
    coffset="${entry##*:}"
    CLUSTERS[$cname]=$coffset
    CLUSTER_ORDER+=("$cname")
done

FORWARD_ZONE="/var/named/forward.${DOMAIN}"
REVERSE_ZONE="/var/named/reverse.${DOMAIN}"

# Check if named.rfc1912.zones needs updating for our domain
NAMED_ZONES="/etc/named.rfc1912.zones"

echo "=== OCP Lab Portal — Infrastructure Setup ==="
echo ""

# --- Pre-flight: check required services are installed ---
echo "=== Checking prerequisites ==="
preflight_ok=true

for svc in named haproxy libvirtd; do
    if ! systemctl list-unit-files "${svc}.service" &>/dev/null; then
        echo "MISSING: ${svc} is not installed."
        echo "  Install it with: dnf install -y ${svc/%d/}"
        preflight_ok=false
    else
        echo "  OK: ${svc} is installed"
    fi
done

for cmd in dig virsh; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "MISSING: '$cmd' command not found."
        case "$cmd" in
            dig) echo "  Install with: dnf install -y bind-utils" ;;
            virsh) echo "  Install with: dnf install -y libvirt" ;;
        esac
        preflight_ok=false
    fi
done

if [ "$preflight_ok" = false ]; then
    echo ""
    echo "STOP: Install missing packages above, then re-run this script."
    exit 1
fi

# --- Check for existing configs not managed by us ---
echo ""
echo "=== Checking existing configurations ==="

check_managed() {
    local file=$1
    local label=$2
    if [ -f "$file" ]; then
        if head -5 "$file" | grep -q "Managed by: OCP Lab Portal"; then
            echo "  ${label}: exists (ours) — will overwrite"
        else
            echo ""
            echo "  WARNING: ${label} exists but was NOT created by this script!"
            echo "  File: ${file}"
            echo "  Review it before proceeding — this script will OVERWRITE it."
            echo ""
            read -rp "  Overwrite ${label}? A backup will be saved. [y/N] " answer
            if [[ ! "$answer" =~ ^[Yy] ]]; then
                echo "  Aborted. Please back up ${file} and re-run."
                exit 1
            fi
            cp "$file" "${file}.bak.$(date +%Y%m%d%H%M%S)"
            echo "  Backup saved: ${file}.bak.*"
        fi
    else
        echo "  ${label}: does not exist — will create"
    fi
}

check_managed "$FORWARD_ZONE" "Forward DNS zone"
check_managed "$REVERSE_ZONE" "Reverse DNS zone"
check_managed "$HAPROXY_CFG" "HAProxy config"

SERIAL=$(date +%Y%m%d%H)

# --- Ensure zone declarations exist in named.rfc1912.zones ---
echo ""
echo "=== Checking BIND zone declarations ==="

add_zone_if_missing() {
    local zone_name=$1
    local zone_file=$2
    local zone_type=$3

    if grep -q "\"${zone_name}\"" "$NAMED_ZONES" 2>/dev/null; then
        echo "  Zone '${zone_name}' already declared"
    else
        echo "  Adding zone '${zone_name}' to $NAMED_ZONES"
        cat >> "$NAMED_ZONES" << ZONEEOF

// ${MANAGED_BY}
zone "${zone_name}" IN {
    type master;
    file "${zone_file}";
    allow-update { none; };
};
ZONEEOF
    fi
}

add_zone_if_missing "${DOMAIN}" "${FORWARD_ZONE}" "forward"
add_zone_if_missing "122.168.192.in-addr.arpa" "${REVERSE_ZONE}" "reverse"

echo ""
echo "=== Generating DNS zone files ==="

# --- Forward zone ---
cat > "$FORWARD_ZONE" << EOF
; ${MANAGED_BY}
\$TTL 1W
@	IN	SOA	ns1.${DOMAIN}.	root (
			${SERIAL}	; serial
			3H		; refresh (3 hours)
			30M		; retry (30 minutes)
			2W		; expiry (2 weeks)
			1W )		; minimum (1 week)
	IN	NS	ns1.${DOMAIN}.
	IN	MX 10	smtp.${DOMAIN}.
;
; Base infrastructure
ns1.${DOMAIN}.		IN	A	${BRIDGE_IP}
smtp.${DOMAIN}.		IN	A	${BRIDGE_IP}
bastion.${DOMAIN}.	IN	A	${BRIDGE_IP}
EOF

for cname in "${CLUSTER_ORDER[@]}"; do
    offset=${CLUSTERS[$cname]}
    cat >> "$FORWARD_ZONE" << EOF
;
; Cluster: ${cname} (offset ${offset})
helper.${cname}.${DOMAIN}.	IN	A	${BRIDGE_IP}
api.${cname}.${DOMAIN}.		IN	A	${BRIDGE_IP}
api-int.${cname}.${DOMAIN}.	IN	A	${BRIDGE_IP}
*.apps.${cname}.${DOMAIN}.	IN	A	${BRIDGE_IP}
;
bootstrap.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset))
master-0.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 1))
master-1.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 2))
master-2.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 3))
worker-0.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 4))
worker-1.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 5))
;
etcd-0.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 1))
etcd-1.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 2))
etcd-2.${cname}.${DOMAIN}.	IN	A	${SUBNET}.$((offset + 3))
_etcd-server-ssl._tcp.${cname}.${DOMAIN}.	86400 IN SRV 0 10 2380 etcd-0.${cname}.${DOMAIN}.
_etcd-server-ssl._tcp.${cname}.${DOMAIN}.	86400 IN SRV 0 10 2380 etcd-1.${cname}.${DOMAIN}.
_etcd-server-ssl._tcp.${cname}.${DOMAIN}.	86400 IN SRV 0 10 2380 etcd-2.${cname}.${DOMAIN}.
EOF
done

echo ";EOF" >> "$FORWARD_ZONE"
echo "  Forward zone written: $FORWARD_ZONE"

# --- Reverse zone ---
cat > "$REVERSE_ZONE" << EOF
; ${MANAGED_BY}
\$TTL 1W
@	IN	SOA	ns1.${DOMAIN}.	root (
			${SERIAL}	; serial
			3H		; refresh (3 hours)
			30M		; retry (30 minutes)
			2W		; expiry (2 weeks)
			1W )		; minimum (1 week)
	IN	NS	ns1.${DOMAIN}.
;
; Base
1	IN	PTR	ns1.${DOMAIN}.
EOF

for cname in "${CLUSTER_ORDER[@]}"; do
    offset=${CLUSTERS[$cname]}
    cat >> "$REVERSE_ZONE" << EOF
;
; Cluster: ${cname} (offset ${offset})
$((offset))	IN	PTR	bootstrap.${cname}.${DOMAIN}.
$((offset + 1))	IN	PTR	master-0.${cname}.${DOMAIN}.
$((offset + 2))	IN	PTR	master-1.${cname}.${DOMAIN}.
$((offset + 3))	IN	PTR	master-2.${cname}.${DOMAIN}.
$((offset + 4))	IN	PTR	worker-0.${cname}.${DOMAIN}.
$((offset + 5))	IN	PTR	worker-1.${cname}.${DOMAIN}.
EOF
done

echo ";EOF" >> "$REVERSE_ZONE"
echo "  Reverse zone written: $REVERSE_ZONE"

# Fix ownership for BIND
chown named:named "$FORWARD_ZONE" "$REVERSE_ZONE"

echo ""
echo "=== Generating HAProxy config ==="

# --- HAProxy ---
cat > "$HAPROXY_CFG" << HAHEAD
${MANAGED_BY}
global
  log         127.0.0.1 local2
  pidfile     /var/run/haproxy.pid
  maxconn     4000
  daemon

defaults
  mode                    tcp
  log                     global
  option                  dontlognull
  option                  redispatch
  retries                 3
  timeout http-request    10s
  timeout queue           1m
  timeout connect         10s
  timeout client          1m
  timeout server          1m
  timeout check           10s
  maxconn                 3000
HAHEAD

# API server (6443) — SNI-based routing
{
echo ""
echo "# Kubernetes API — SNI routing to per-cluster backends"
echo "frontend api-server-6443"
echo "  bind ${BRIDGE_IP}:6443"
echo "  mode tcp"
echo "  tcp-request inspect-delay 5s"
echo "  tcp-request content accept if { req_ssl_hello_type 1 }"
for cname in "${CLUSTER_ORDER[@]}"; do
    echo "  use_backend api-${cname}-6443 if { req.ssl_sni -i api.${cname}.${DOMAIN} }"
    echo "  use_backend api-${cname}-6443 if { req.ssl_sni -i api-int.${cname}.${DOMAIN} }"
done
echo "  default_backend api-${CLUSTER_ORDER[0]}-6443"
} >> "$HAPROXY_CFG"

# Machine Config Server (22623) — SNI-based routing
{
echo ""
echo "# Machine Config Server — SNI routing"
echo "frontend mcs-22623"
echo "  bind ${BRIDGE_IP}:22623"
echo "  mode tcp"
echo "  tcp-request inspect-delay 5s"
echo "  tcp-request content accept if { req_ssl_hello_type 1 }"
for cname in "${CLUSTER_ORDER[@]}"; do
    echo "  use_backend mcs-${cname}-22623 if { req.ssl_sni -i api-int.${cname}.${DOMAIN} }"
done
echo "  default_backend mcs-${CLUSTER_ORDER[0]}-22623"
} >> "$HAPROXY_CFG"

# Ingress HTTPS (443) — SNI-based routing
{
echo ""
echo "# Ingress HTTPS — SNI routing for *.apps.<cluster>"
echo "frontend ingress-https-443"
echo "  bind ${BRIDGE_IP}:443"
echo "  mode tcp"
echo "  tcp-request inspect-delay 5s"
echo "  tcp-request content accept if { req_ssl_hello_type 1 }"
for cname in "${CLUSTER_ORDER[@]}"; do
    echo "  use_backend ingress-https-${cname}-443 if { req.ssl_sni -m end .apps.${cname}.${DOMAIN} }"
done
echo "  default_backend ingress-https-${CLUSTER_ORDER[0]}-443"
} >> "$HAPROXY_CFG"

# Ingress HTTP (80) — Host header routing (mode http)
{
echo ""
echo "# Ingress HTTP — Host header routing for *.apps.<cluster>"
echo "frontend ingress-http-80"
echo "  bind ${BRIDGE_IP}:80"
echo "  mode http"
for cname in "${CLUSTER_ORDER[@]}"; do
    echo "  use_backend ingress-http-${cname}-80 if { hdr_end(host) -i .apps.${cname}.${DOMAIN} }"
done
echo "  default_backend ingress-http-${CLUSTER_ORDER[0]}-80"
} >> "$HAPROXY_CFG"

# Per-cluster backends
for cname in "${CLUSTER_ORDER[@]}"; do
    offset=${CLUSTERS[$cname]}
    BS="${SUBNET}.$((offset))"
    M0="${SUBNET}.$((offset + 1))"
    M1="${SUBNET}.$((offset + 2))"
    M2="${SUBNET}.$((offset + 3))"
    W0="${SUBNET}.$((offset + 4))"
    W1="${SUBNET}.$((offset + 5))"

    cat >> "$HAPROXY_CFG" << HABACK

# ---- Cluster: ${cname} (offset ${offset}) ----
backend api-${cname}-6443
  mode tcp
  option httpchk GET /readyz HTTP/1.0
  option log-health-checks
  balance roundrobin
  default-server inter 10s downinter 5s rise 2 fall 3 slowstart 60s maxconn 250 maxqueue 256 weight 100
  server ${cname}-bootstrap ${BS}:6443 check check-ssl verify none backup
  server ${cname}-master-0 ${M0}:6443 check check-ssl verify none
  server ${cname}-master-1 ${M1}:6443 check check-ssl verify none
  server ${cname}-master-2 ${M2}:6443 check check-ssl verify none

backend mcs-${cname}-22623
  mode tcp
  balance roundrobin
  server ${cname}-bootstrap ${BS}:22623 check inter 1s backup
  server ${cname}-master-0 ${M0}:22623 check inter 1s
  server ${cname}-master-1 ${M1}:22623 check inter 1s
  server ${cname}-master-2 ${M2}:22623 check inter 1s

backend ingress-https-${cname}-443
  mode tcp
  balance source
  server ${cname}-worker-0 ${W0}:443 check inter 1s
  server ${cname}-worker-1 ${W1}:443 check inter 1s

backend ingress-http-${cname}-80
  mode http
  balance source
  server ${cname}-worker-0 ${W0}:80 check inter 1s
  server ${cname}-worker-1 ${W1}:80 check inter 1s
HABACK
done

echo "  HAProxy config written: $HAPROXY_CFG"

# Validate HAProxy config
echo ""
echo "=== Validating HAProxy config ==="
if haproxy -c -f "$HAPROXY_CFG"; then
    echo "  Config valid."
else
    echo "  FAIL: HAProxy config validation failed!"
    exit 1
fi

# --- SELinux ---
# HAProxy needs to bind non-standard ports (6443, 22623) and connect to backends.
# BIND needs to write master zone files.
echo ""
echo "=== Configuring SELinux ==="
if command -v getenforce &>/dev/null && [ "$(getenforce)" != "Disabled" ]; then
    # Allow HAProxy to bind/connect to any port (covers 6443, 22623, etc.)
    if ! getsebool haproxy_connect_any 2>/dev/null | grep -q 'on$'; then
        setsebool -P haproxy_connect_any on
        echo "  Set haproxy_connect_any = on"
    else
        echo "  haproxy_connect_any already on"
    fi

    # Allow BIND to write master zone files
    if ! getsebool named_write_master_zones 2>/dev/null | grep -q 'on$'; then
        setsebool -P named_write_master_zones on
        echo "  Set named_write_master_zones = on"
    else
        echo "  named_write_master_zones already on"
    fi

    # Ensure HAProxy port labels exist for non-standard ports
    if command -v semanage &>/dev/null; then
        for port in 6443 22623; do
            if ! semanage port -l 2>/dev/null | grep -q "http_port_t.*\b${port}\b"; then
                semanage port -a -t http_port_t -p tcp "$port" 2>/dev/null || \
                semanage port -m -t http_port_t -p tcp "$port" 2>/dev/null || true
                echo "  Labeled port $port as http_port_t"
            else
                echo "  Port $port already labeled"
            fi
        done
    fi

    # Fix SELinux context on zone files and HAProxy config
    restorecon -v "$FORWARD_ZONE" "$REVERSE_ZONE" 2>/dev/null || true
    restorecon -v "$HAPROXY_CFG" 2>/dev/null || true
    echo "  SELinux contexts restored on config files"
else
    echo "  SELinux disabled — skipping"
fi

# --- Restrict /kvm access for lab users ---
echo ""
echo "=== Configuring /kvm access restrictions ==="
groupadd -f labusers
if [ -d "/kvm" ]; then
    # Group-level ACL: labusers get read+execute only (no write/delete)
    setfacl -R -m g:labusers:r-X /kvm 2>/dev/null && \
        echo "  Set read-only ACL for labusers on /kvm" || \
        echo "  WARN: Could not set ACL on /kvm (install acl package?)"
    # Default ACL: new files/dirs inherit the restriction
    setfacl -R -d -m g:labusers:r-X /kvm 2>/dev/null || true
else
    echo "  /kvm does not exist — skipping (will apply when /kvm is created)"
fi

# Open firewall ports for OCP traffic on the libvirt zone
# VMs reach HAProxy via virbr0 which is in the 'libvirt' zone.
# Without these rules, VMs get "connection refused" on OCP ports.
echo ""
echo "=== Configuring firewall ==="
if command -v firewall-cmd &>/dev/null && firewall-cmd --state &>/dev/null; then
    LIBVIRT_ZONE="libvirt"
    OCP_PORTS=(6443/tcp 22623/tcp 443/tcp 80/tcp)
    for port in "${OCP_PORTS[@]}"; do
        if ! firewall-cmd --zone="$LIBVIRT_ZONE" --query-port="$port" &>/dev/null; then
            firewall-cmd --zone="$LIBVIRT_ZONE" --add-port="$port" &>/dev/null
            firewall-cmd --zone="$LIBVIRT_ZONE" --add-port="$port" --permanent &>/dev/null
            echo "  Opened $port in $LIBVIRT_ZONE zone"
        else
            echo "  $port already open in $LIBVIRT_ZONE zone"
        fi
    done
else
    echo "  firewalld not running — skipping (ensure ports 6443,22623,443,80 are open for VMs)"
fi

# Reload services
echo ""
echo "=== Reloading services ==="
systemctl reload named || systemctl restart named
echo "  named reloaded."
systemctl reload haproxy || systemctl restart haproxy
echo "  haproxy reloaded."

# Verify DNS
echo ""
echo "=== Verifying DNS resolution ==="
for cname in "${CLUSTER_ORDER[@]}"; do
    offset=${CLUSTERS[$cname]}
    resolved=$(dig +short api.${cname}.${DOMAIN} @127.0.0.1 2>/dev/null || echo "FAILED")
    echo "  api.${cname}.${DOMAIN} -> ${resolved} (expected ${BRIDGE_IP})"
    resolved=$(dig +short bootstrap.${cname}.${DOMAIN} @127.0.0.1 2>/dev/null || echo "FAILED")
    echo "  bootstrap.${cname}.${DOMAIN} -> ${resolved} (expected ${SUBNET}.$((offset)))"
done

echo ""
echo "=== Setup complete ==="
echo "Cluster slots configured:"
for cname in "${CLUSTER_ORDER[@]}"; do
    offset=${CLUSTERS[$cname]}
    echo "  ${cname}: IPs ${SUBNET}.$((offset)) - ${SUBNET}.$((offset + 5))"
done
echo ""
echo "No further service restarts needed — HAProxy health checks handle availability."
echo "Deploy clusters from the portal or CLI using these predefined slot names."
