#!/bin/bash
set -euo pipefail

# =============================================================================
# OpenShift UPI Bare-Metal Deployment Script (KVM/libvirt)
#
# Usage: ./create.sh <ocp_version> [cluster_name] [ip_offset] [network_type]
#   ocp_version  - e.g. 4.16.5
#   cluster_name - optional, defaults to "upi". Use distinct names to run
#                  multiple clusters in parallel without collision.
#   network_type - optional, OVNKubernetes (default) or OpenShiftSDN (4.14 and below)
# =============================================================================

# --- CONFIGURATION ---

# Source site config if available (generated by the Lab Portal setup wizard)
if [ -f /etc/ocp-lab.conf ]; then
    # shellcheck source=/dev/null
    source /etc/ocp-lab.conf
fi

# Base domain — from env, /etc/ocp-lab.conf, or default
BASE_DOMAIN="${BASE_DOMAIN:-example.com}"
STORAGE_DIR="${STORAGE_DIR:-/kvm}"

VERSION="${1:-}"
CLUSTER_NAME="${2:-upi}"

if [ -z "$VERSION" ]; then
    echo "Usage: $0 <ocp_version> [cluster_name]"
    echo "  cluster_name defaults to 'upi' if omitted"
    exit 1
fi

# Use Absolute Paths to prevent path resolution errors
BASE_DIR="$STORAGE_DIR/client_tools/$VERSION"
INSTALL_DIR="$STORAGE_DIR/clusters/${CLUSTER_NAME}-${VERSION}"
MIRROR_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$VERSION"

# Networking — each cluster gets a unique IP block based on cluster name hash
# Default network: 192.168.122.0/24
BRIDGE_IP="192.168.122.1"
NETMASK="255.255.255.0"

# IP offset — configurable via 3rd argument or IP_OFFSET env var.
# Defaults to 110 for backward compatibility with existing DNS zones.
# For parallel clusters, pass a different offset (e.g., ./ocp-upi-deploy.sh 4.20.1 lab 150)
IP_OFFSET="${3:-${IP_OFFSET:-110}}"
NETWORK_TYPE="${4:-OVNKubernetes}"

# Derive per-cluster MAC suffix from offset
MAC_BASE=$(printf "%02x" "$IP_OFFSET")

# Per-cluster VM name prefix: vm-<cluster>-<role>
VM_PREFIX="vm-${CLUSTER_NAME}"

# Pull secret and SSH key — configurable via environment
PULL_SECRET_FILE="${PULL_SECRET_FILE:-/root/pull-secret.txt}"
SSH_KEY_FILE="${SSH_KEY_FILE:-$HOME/.ssh/id_ed25519.pub}"

# --- CLEANUP TRAP ---
cleanup() {
    echo ""
    echo "Caught signal — cleaning up..."
    systemctl stop "csr-approver@${CLUSTER_NAME}.service" 2>/dev/null || true
    echo "Cleanup complete."
}

trap cleanup EXIT INT TERM

# --- PRE-FLIGHT CHECKS ---
echo "=== Pre-flight checks ==="

preflight_ok=true

# Required commands
for cmd in openshift-install oc coreos-installer virsh virt-install curl jq python3; do
    # openshift-install and oc will be downloaded, skip if not yet present
    if [[ "$cmd" == "openshift-install" || "$cmd" == "oc" ]]; then
        continue
    fi
    if ! command -v "$cmd" &>/dev/null; then
        echo "FAIL: '$cmd' is not installed."
        preflight_ok=false
    fi
done

# Pull secret
if [ ! -f "$PULL_SECRET_FILE" ]; then
    echo "FAIL: Pull secret not found at $PULL_SECRET_FILE"
    echo "      Set PULL_SECRET_FILE=/path/to/pull-secret.txt to override."
    preflight_ok=false
fi

# SSH key
if [ ! -f "$SSH_KEY_FILE" ]; then
    echo "FAIL: SSH public key not found at $SSH_KEY_FILE"
    echo "      Set SSH_KEY_FILE=/path/to/key.pub to override."
    preflight_ok=false
fi

# libvirt default network
if ! virsh net-info default &>/dev/null; then
    echo "FAIL: libvirt 'default' network does not exist."
    preflight_ok=false
elif [ "$(virsh net-info default 2>/dev/null | awk '/^Active:/{print $2}')" != "yes" ]; then
    echo "FAIL: libvirt 'default' network is not active. Run: virsh net-start default"
    preflight_ok=false
fi

# RAM check — need at least 48 GB for the full cluster (5 nodes × 16 GB = 80 GB ideal, 48 GB minimum)
TOTAL_RAM_KB=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
TOTAL_RAM_GB=$(( TOTAL_RAM_KB / 1024 / 1024 ))
REQUIRED_RAM_GB=48
if [ "$TOTAL_RAM_GB" -lt "$REQUIRED_RAM_GB" ]; then
    echo "WARN: System has ${TOTAL_RAM_GB} GB RAM, cluster needs ~${REQUIRED_RAM_GB} GB."
    echo "      Deployment may fail or be very slow due to swapping."
fi

# Disk space check — need at least 750 GB on /kvm (or wherever INSTALL_DIR lives)
INSTALL_MOUNT=$(df --output=avail -B1G "$( dirname "$INSTALL_DIR" )" 2>/dev/null | tail -1 | tr -d ' ')
if [ -n "$INSTALL_MOUNT" ] && [ "$INSTALL_MOUNT" -lt 750 ]; then
    echo "WARN: Only ${INSTALL_MOUNT} GB available for VM disks. 6 VMs x 120 GB = 720 GB needed."
fi

# os-variant check
if command -v osinfo-query &>/dev/null; then
    if ! osinfo-query os | grep -q 'rhel9.0'; then
        echo "WARN: os-variant 'rhel9.0' not found in osinfo-db."
        echo "      Will attempt 'rhel9-unknown' as fallback."
        OS_VARIANT="rhel9-unknown"
    else
        OS_VARIANT="rhel9.0"
    fi
else
    echo "WARN: osinfo-query not found, defaulting os-variant to 'rhel9.0'."
    OS_VARIANT="rhel9.0"
fi

# DNS sanity check — verify at least the API endpoint resolves
API_HOSTNAME="api.${CLUSTER_NAME}.${BASE_DOMAIN}"
if command -v dig &>/dev/null; then
    if ! dig +short "$API_HOSTNAME" 2>/dev/null | grep -q .; then
        echo "WARN: DNS lookup for '$API_HOSTNAME' returned nothing."
        echo "      Ensure DNS is configured for the cluster."
    fi
elif command -v nslookup &>/dev/null; then
    if ! nslookup "$API_HOSTNAME" &>/dev/null; then
        echo "WARN: DNS lookup for '$API_HOSTNAME' failed."
    fi
fi

if [ "$preflight_ok" = false ]; then
    echo ""
    echo "Pre-flight checks FAILED. Fix the issues above and re-run."
    exit 1
fi

echo "=== Pre-flight checks passed ==="
echo ""

mkdir -p "$BASE_DIR" "$INSTALL_DIR"

# --- 1. TOOLS MANAGEMENT ---
install_binary() {
    local binary=$1
    sudo cp "$BASE_DIR/$binary" "/usr/local/bin/${binary}.tmp.$$"
    sudo chmod 0755 "/usr/local/bin/${binary}.tmp.$$"
    # Atomic swap via mv — existing processes keep their fd to the old inode
    sudo mv "/usr/local/bin/${binary}.tmp.$$" "/usr/local/bin/$binary"
}

check_and_get_tool() {
    local tool=$1; local binary=$2

    # Already installed and matches this version — nothing to do
    if [[ -f "/usr/local/bin/$binary" ]] && [[ "$($binary version 2>/dev/null)" == *"$VERSION"* ]]; then
        echo "$binary $VERSION is already active."
        return
    fi

    # Cached in BASE_DIR from a previous run — install without downloading
    if [[ -f "$BASE_DIR/$binary" ]]; then
        echo "$binary found in cache ($BASE_DIR), installing..."
        install_binary "$binary"
        if [[ "$binary" == "oc" ]] && [[ -f "$BASE_DIR/kubectl" ]]; then
            install_binary "kubectl"
        fi
        return
    fi

    # Download, verify, extract, install
    echo "Downloading $tool..."
    curl --fail -SL "$MIRROR_URL/${tool}-linux.tar.gz" -o "$BASE_DIR/${tool}.tar.gz"

    local sha_file="$BASE_DIR/${tool}-sha256.txt"
    if curl --fail -sSL "$MIRROR_URL/sha256sum.txt" -o "$sha_file" 2>/dev/null; then
        local expected
        expected=$(grep "${tool}-linux" "$sha_file" | grep -v arm64 | grep -v ppc64 | grep -v s390x | head -1 | awk '{print $1}' || true)
        if [ -n "$expected" ]; then
            local actual
            actual=$(sha256sum "$BASE_DIR/${tool}.tar.gz" | awk '{print $1}')
            if [ "$expected" != "$actual" ]; then
                echo "FAIL: Checksum mismatch for ${tool}-linux.tar.gz"
                echo "  Expected: $expected"
                echo "  Got:      $actual"
                exit 1
            fi
            echo "Checksum verified for $tool."
        fi
    fi

    tar -xzf "$BASE_DIR/${tool}.tar.gz" -C "$BASE_DIR"
    # Remove tarball after extraction to save disk space
    rm -f "$BASE_DIR/${tool}.tar.gz" "$BASE_DIR/${tool}-sha256.txt"

    install_binary "$binary"
    if [[ "$binary" == "oc" ]] && [[ -f "$BASE_DIR/kubectl" ]]; then
        install_binary "kubectl"
    fi
}

check_and_get_tool "openshift-install" "openshift-install"
check_and_get_tool "openshift-client" "oc"

# --- 2. LIVE ISO RETRIEVAL ---
MASTER_TEMPLATE_ISO="$BASE_DIR/rhcos-live-MASTER.iso"

if [ -f "$MASTER_TEMPLATE_ISO" ]; then
    echo "Using cached RHCOS ISO: $MASTER_TEMPLATE_ISO"
else
    echo "Querying RHCOS metadata for x86_64 Live ISO..."
    STREAM_JSON=$(openshift-install coreos print-stream-json)

    # Parse JSON for the ISO URL — prefer jq, fall back to python3
    if command -v jq &>/dev/null; then
        ISO_URL=$(echo "$STREAM_JSON" | jq -r '.architectures.x86_64.artifacts.metal.formats.iso.disk.location')
    else
        ISO_URL=$(echo "$STREAM_JSON" | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['architectures']['x86_64']['artifacts']['metal']['formats']['iso']['disk']['location'])")
    fi

    if [ -z "$ISO_URL" ] || [ "$ISO_URL" = "null" ]; then
        echo "FAIL: Could not extract ISO URL from coreos stream metadata."
        exit 1
    fi
    echo "Downloading Master ISO template..."
    curl --fail -SL -o "$MASTER_TEMPLATE_ISO" "$ISO_URL"

    # Verify ISO checksum if available in stream JSON
    if command -v jq &>/dev/null; then
        EXPECTED_SHA=$(echo "$STREAM_JSON" | jq -r '.architectures.x86_64.artifacts.metal.formats.iso.disk.sha256 // empty')
        if [ -n "$EXPECTED_SHA" ]; then
            ACTUAL_SHA=$(sha256sum "$MASTER_TEMPLATE_ISO" | awk '{print $1}')
            if [ "$EXPECTED_SHA" != "$ACTUAL_SHA" ]; then
                echo "FAIL: ISO checksum mismatch."
                echo "  Expected: $EXPECTED_SHA"
                echo "  Got:      $ACTUAL_SHA"
                rm -f "$MASTER_TEMPLATE_ISO"
                exit 1
            fi
            echo "ISO checksum verified."
        fi
    fi
fi

# --- 3. INSTALL-CONFIG & IGNITION GENERATION ---
cd "$INSTALL_DIR"

echo "Creating install-config.yaml..."

# Pre-read secrets so we don't need command substitution inside the heredoc
PULL_SECRET=$(cat "$PULL_SECRET_FILE")
SSH_KEY=$(cat "$SSH_KEY_FILE")

cat > install-config.yaml <<_INSTALL_CONFIG_
apiVersion: v1
baseDomain: ${BASE_DOMAIN}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ${CLUSTER_NAME}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: ${NETWORK_TYPE}
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '${PULL_SECRET}'
sshKey: '${SSH_KEY}'
_INSTALL_CONFIG_

echo "Generating Ignition configs..."
cp -f install-config.yaml install-config.yaml_backup
openshift-install create manifests --dir=.
openshift-install create ignition-configs --dir=.
# Restore backup as the install tool consumes the original
cp install-config.yaml_backup install-config.yaml

# --- 4. PER-NODE CUSTOMIZATION & DEPLOY FUNCTION ---
deploy_node() {
    local name=$1; local ram=$2; local cpu=$3; local mac=$4; local role=$5; local ip=$6; local hostname=$7
    local NODE_ISO="$INSTALL_DIR/${name}.iso"

    # Add DHCP reservation in libvirt default network so the VM always
    # gets the correct IP, regardless of kernel args or NetworkManager state.
    echo "Adding DHCP reservation: $mac -> $ip ($hostname)"
    virsh net-update default add ip-dhcp-host \
        "<host mac='$mac' name='$hostname' ip='$ip'/>" \
        --live --config 2>/dev/null || true

    echo "--- Creating Node-Specific ISO: $(basename "$NODE_ISO") ---"

    # Customize using the Master as source and Node-specific name as output
    coreos-installer iso customize \
        --dest-ignition "$INSTALL_DIR/$role.ign" \
        --dest-device /dev/vda \
        --dest-console tty0 \
        --dest-console ttyS0,115200n8 \
        --dest-karg-append "ip=$ip::$BRIDGE_IP:$NETMASK:$hostname::none" \
        --dest-karg-append "nameserver=$BRIDGE_IP" \
        -o "$NODE_ISO" "$MASTER_TEMPLATE_ISO"

    if [ ! -f "$NODE_ISO" ]; then
        echo "FAIL: ISO creation failed for $name"
        exit 1
    fi

    # Remove stale SSH host keys for this IP (VMs get new keys each deploy)
    ssh-keygen -R "$ip" 2>/dev/null || true

    echo "Provisioning VM: $name"
    virsh destroy "$name" 2>/dev/null || true
    virsh undefine "$name" --remove-all-storage 2>/dev/null || true

    virt-install --name "$name" \
        --ram "$ram" \
        --vcpus "$cpu" \
        --cpu host-passthrough \
        --disk size=120,bus=virtio \
        --network network=default,mac="$mac" \
        --graphics vnc,listen=127.0.0.1 \
        --video virtio \
        --cdrom "$NODE_ISO" \
        --boot hd,cdrom \
        --noautoconsole \
        --check disk_size=off \
        --os-variant "$OS_VARIANT"

    # Wait for CoreOS to install to disk and shut off, then fix boot order.
    # --cdrom sets CDROM bootindex=1 which overrides --boot, so the VM shuts
    # down after coreos-installer writes to /dev/vda. We remove the CDROM,
    # set boot to HDD only, and restart.
    echo "Waiting for $name to finish CoreOS install..."
    while [ "$(virsh domstate "$name" 2>/dev/null)" = "running" ]; do
        sleep 5
    done
    echo "$name shut off — fixing boot order and restarting..."
    virt-xml "$name" --edit --boot hd
    virt-xml "$name" --remove-device --disk device=cdrom 2>/dev/null || true
    virsh start "$name"
    echo "$name restarted from HDD."
}

# --- 5. EXECUTION LOOP ---
# Per-cluster VM names, MACs, and IPs derived from CLUSTER_NAME + IP_OFFSET
# Usage: Name | RAM | CPU | MAC | Role | IP | Hostname
deploy_node "${VM_PREFIX}-bootstrap" 16384 4  "52:54:00:${MAC_BASE}:00:10" "bootstrap" "192.168.122.$(( IP_OFFSET ))"     "bootstrap.${CLUSTER_NAME}.${BASE_DOMAIN}"
deploy_node "${VM_PREFIX}-master-0"  16384 4  "52:54:00:${MAC_BASE}:00:11" "master"    "192.168.122.$(( IP_OFFSET + 1 ))" "master-0.${CLUSTER_NAME}.${BASE_DOMAIN}"
deploy_node "${VM_PREFIX}-master-1"  16384 4  "52:54:00:${MAC_BASE}:00:12" "master"    "192.168.122.$(( IP_OFFSET + 2 ))" "master-1.${CLUSTER_NAME}.${BASE_DOMAIN}"
deploy_node "${VM_PREFIX}-master-2"  16384 4  "52:54:00:${MAC_BASE}:00:13" "master"    "192.168.122.$(( IP_OFFSET + 3 ))" "master-2.${CLUSTER_NAME}.${BASE_DOMAIN}"
deploy_node "${VM_PREFIX}-worker-0"  16384 2  "52:54:00:${MAC_BASE}:00:14" "worker"    "192.168.122.$(( IP_OFFSET + 4 ))" "worker-0.${CLUSTER_NAME}.${BASE_DOMAIN}"
deploy_node "${VM_PREFIX}-worker-1"  16384 2  "52:54:00:${MAC_BASE}:00:15" "worker"    "192.168.122.$(( IP_OFFSET + 5 ))" "worker-1.${CLUSTER_NAME}.${BASE_DOMAIN}"

# --- 6. MONITORING & CSR APPROVAL ---
export KUBECONFIG="$INSTALL_DIR/auth/kubeconfig"

echo "Starting CSR auto-approver service for ${CLUSTER_NAME}..."
systemctl start "csr-approver@${CLUSTER_NAME}.service" 2>/dev/null || \
    echo "WARN: Could not start csr-approver service — approve CSRs manually if needed"

echo "Waiting for Bootstrap (this takes approx 20 mins)..."
openshift-install wait-for bootstrap-complete --dir=. --log-level=info

echo "Deleting Bootstrap VM to reclaim RAM..."
virsh destroy "${VM_PREFIX}-bootstrap" 2>/dev/null && virsh undefine "${VM_PREFIX}-bootstrap" --remove-all-storage 2>/dev/null

echo "Waiting for Final Installation..."
openshift-install wait-for install-complete --dir=. --log-level=info

# Stop CSR approver if still running (it self-terminates, but just in case)
systemctl stop "csr-approver@${CLUSTER_NAME}.service" 2>/dev/null || true

# --- 7. FINAL BANNER ---
# Grant labusers group read-write access to cluster files (kubeconfig, etc.)
if getent group labusers &>/dev/null; then
    setfacl -R -m g:labusers:rwX -m m::rwx "$INSTALL_DIR"
    setfacl -R -d -m g:labusers:rwX -m m::rwx "$INSTALL_DIR"
fi

# Update the dynamic MOTD that shows all active clusters
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -x "$SCRIPT_DIR/update-motd.sh" ]; then
    "$SCRIPT_DIR/update-motd.sh"
else
    echo "WARN: update-motd.sh not found at $SCRIPT_DIR — MOTD not updated."
fi

KUBE_PASS=$(cat "$INSTALL_DIR/auth/kubeadmin-password" 2>/dev/null || echo "UNKNOWN")
CONSOLE="console-openshift-console.apps.${CLUSTER_NAME}.${BASE_DOMAIN}"
echo ""
echo "==========================================="
echo "  Cluster ${CLUSTER_NAME} (OCP ${VERSION}) is ready!"
echo "  Console:    https://$CONSOLE"
echo "  Username:   kubeadmin"
echo "  Password:   $KUBE_PASS"
echo "  KUBECONFIG: export KUBECONFIG=$INSTALL_DIR/auth/kubeconfig"
echo "==========================================="
